# Spring
spring:
  # H2 DataBase 
  h2:
    console:
      enabled: true
      path: /console
    jpa:
      show-sql: true
  # JDBC
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  # Thymeleaf
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
# DEVTOOLS (DevToolsProperties)
  devtools:
    livereload:
      enabled: true
# Server port
server:
  port: 8991